version: "3"
services:
  app:
    image: node:11.10.1
    command: bash -c "yarn && yarn start"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - ELASTICSEARCH_URL=http://es:9200
    ports:
      - 3000:3000
    depends_on:
      - es

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"